export interface Game{
    id: number,
    ateamid: number,
    ateam: string,
    updated: string,
    winnerteamid: number,
    round: number,
    agoals: number,
    venue: string,
    is_grand_final: number,
    hbehinds: number,
    hteamid: number,
    complete: number,
    abehinds: number,
    winner: string,
    hscore: number,
    tz: string,
    hteam: string,
    is_final: number,
    hgoals: number,
    date: string,
    ascore: number,
    year: number,
}